export const MINIO_CLIENT = 'MINIO_CLIENT';
export const INTERNAL_MINIO_CLIENT = 'INTERNAL_MINIO_CLIENT';
export const STORAGE_BUCKET_NAME = 'STORAGE_BUCKET_NAME';
export const DEFAULT_PRESIGNED_URL_EXPIRY = 3600;
