export enum FilesErrorCodes {
  //Storage infrastructure errors
  STORAGE_CONNECTION_ERROR = 'STORAGE_CONNECTION_ERROR',
  STORAGE_UPLOAD_FAILED = 'STORAGE_UPLOAD_FAILED',
  STORAGE_DELETE_FAILED = 'STORAGE_DELETE_FAILED',
  //Files domain errors
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  FOLDER_CYCLE_DETECTED = 'FOLDER_CYCLE_DETECTED',
  INVALID_PATH = 'INVALID_PATH',
  INVALID_PERMISSION = 'INVALID_PERMISSION',
}
