export enum GroupErrorCodes {
  GROUP_NOT_FOUND = 'GROUP_NOT_FOUND',
  GROUP_NAME_EXISTS = 'GROUP_NAME_EXISTS',
  GROUP_USER_NOT_MEMBER = 'GROUP_USER_NOT_MEMBER',
  GROUP_USER_ALREADY_MEMBER = 'GROUP_USER_ALREADY_MEMBER',
  GROUP_PERMISSION_DENIED = 'GROUP_PERMISSION_DENIED',
  GROUP_OPERATION_FAILED = 'GROUP_OPERATION_FAILED',
}
