export const JWT_ACCESS_EXPIRES_IN = 'JWT_ACCESS_EXPIRES_IN';
export const JWT_REFRESH_EXPIRES_IN = 'JWT_REFRESH_EXPIRES_IN';
export const JWT_PENDING_EXPIRES_IN = 'JWT_PENDING_EXPIRES_IN';
export const JWT_SECRET = 'JWT_SECRET';
