export enum AuthErrorCodes {
  INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  TOKEN_REUSE = 'AUTH_TOKEN_REUSE',
  UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  FORBIDDEN = 'AUTH_FORBIDDEN',
  MISSING_PERMISSIONS = 'AUTH_MISSING_PERMISSIONS',
}
