export enum UserErrorCodes {
  WEAK_PASSWORD = 'USER_WEAK_PASSWORD',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_ALREADY_EXISTS = 'USER_EMAIL_ALREADY_EXISTS',
  USERNAME_ALREADY_EXISTS = 'USER_USERNAME_ALREADY_EXISTS',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
}
