export enum TeamErrorCodes {
  TEAM_NOT_FOUND = 'TEAM_NOT_FOUND',
  TEAM_USER_NOT_MEMBER = 'TEAM_USER_NOT_MEMBER',
  TEAM_USER_ALREADY_MEMBER = 'TEAM_USER_ALREADY_MEMBER',
  TEAM_PERMISSION_DENIED = 'TEAM_PERMISSION_DENIED',
  TEAM_OPERATION_FAILED = 'TEAM_OPERATION_FAILED',
}
