export enum TeamPermission {
  UPDATE_TEAM_DETAILS = 'UPDATE_TEAM_DETAILS',
  DELETE_TEAM = 'DELETE_TEAM',
  ADD_MEMBER = 'ADD_MEMBER',
  ADD_MANAGER = 'ADD_MANAGER',
  ADD_OWNER = 'ADD_OWNER',
  REMOVE_MEMBER = 'REMOVE_MEMBER',
  REMOVE_MANAGER = 'REMOVE_MANAGER',
  REMOVE_OWNER = 'REMOVE_OWNER',
  PROMOTE_TO_MANAGER = 'PROMOTE_TO_MANAGER',
  PROMOTE_TO_OWNER = 'PROMOTE_TO_OWNER',
  DEMOTE_MANAGER = 'DEMOTE_MANAGER',
  DEMOTE_OWNER = 'DEMOTE_OWNER',
}
