export enum FilesErrorSource {
  LOAD_CONTENT = 'LOAD_CONTENT',
  CREATE_FOLDER = 'CREATE_FOLDER',
  DELETE_RESOURCE = 'DELETE_RESOURCE',
  GET_DOWNLOAD_URL = 'GET_DOWNLOAD_URL',
  UPLOAD_FLOW = 'UPLOAD_FLOW',
}
